name: main
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        name: Install NodeJS
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install

      - name: Run tests
        run: pnpm test
