name: publish
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        name: Install NodeJS
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install

      - name: Build
        run: |
          pnpm build
          pnpm typedoc

      - uses: JS-DevTools/npm-publish@v3
        name: Publish npm package
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}

      - uses: s0/git-publish-subdir-action@develop
        name: Publish docs
        env:
          BRANCH: docs
          FOLDER: docs
          REPO: self
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
